module.exports = {
  images: {
    domains: ["media.graphcms.com"],
  },
  env: {
    GRAPHCMS_ENDPOINT: process.env.GRAPHCMS_ENDPOINT,
    STREAM_API_KEY: process.env.NEXT_STREAM_API_KEY,
    STREAM_API_SECRET: process.env.NEXT_STREAM_API_SECRET,
    STREAM_APP_ID: process.env.NEXT_STREAM_APP_ID,
    NEXT_EMAIL_PASSWORD: process.env.NEXT_EMAIL_PASSWORD,
    NEXT_EMAIL: process.env.NEXT_EMAIL,
    NEXT_WEB_CLIENT_FACEBOOK_ID: process.env.NEXT_WEB_CLIENT_FACEBOOK_ID,
    NEXT_WEB_CLIENT_FACEBOOK_SECRETE: process.env.NEXT_WEB_CLIENT_FACEBOOK_SECRETE,
    NEXT_WEB_CLIENT_GOOGLE_ID: process.env.NEXT_WEB_CLIENT_GOOGLE_ID,
    NEXT_WEB_CLIENT_GOOGLE_SECRETE: process.env.NEXT_WEB_CLIENT_GOOGLE_SECRETE,
    NEXT_AUTH_URL: process.env.NEXT_AUTH_URL,
  },
};
